[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max_old_space_size=4096"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors 'self' https://www.youtube.com https://youtu.be"
    Secure-Referrer-Policy = "origin-when-cross-origin"

[[redirects]]
  from = "/aboutus"
  to = "/#about"
  status = 301
  [[redirects]]
  from = "/capabilities"
  to = "/#capabilities"
  status = 301
  [[redirects]]
  from = "/industry"
  to = "/#industries"
  status = 301