[build]
  publish = "public"
  command = "gatsby build"

[build.environment]
  NODE_VERSION = "14"
  NODE_OPTIONS = "--max_old_space_size=4096"

  [[redirects]]
  from = "/aboutus"
  to = "/#about"
  status = 301
  [[redirects]]
  from = "/capabilities"
  to = "/#capabilities"
  status = 301
  [[redirects]]
  from = "/industry"
  to = "/#industries"
  status = 301